### ISSUE TITLE
Just FYI regarding requestbodyvar

### ISSUE THREAD

**Issue by francislavoie** [RussellLuo/caddy-ext#1]
There's already a module that does that: https://caddyserver.com/docs/modules/http.handlers.json_parse

There may be some differences though.

**Comment by RussellLuo** [comment]
@francislavoie Thank you for the useful information! I wouldn't have implemented `requestbodyvar` if I had known this module.

That being said, I think https://github.com/tidwall/gjson (used by `requestbodyvar`) is more powerful ;)
