### ISSUE TITLE
Add to Caddy download page

### ISSUE THREAD

**Issue by AndreKR** [RussellLuo/caddy-ext#11]
@RussellLuo I see you have other Caddy plugins registered, but this one seems to be missing on the Caddy download page.

**Comment by AndreKR** [comment]
Oh, sorry, didn't see it's a monorepo. I meant the `layer4` plugin, the one that adds (some) Caddyfile support for caddy-l4.

**Comment by RussellLuo** [comment]
Done! Now `layer4` can be downloaded from https://caddyserver.com/download :)

**Comment by RussellLuo** [comment]
I'm going to close this issue, feel free to open issues if you have other questions :)
