### ISSUE TITLE
Release new version of Ratelimit module

### ISSUE THREAD

**Issue by Flameborn** [RussellLuo/caddy-ext#12]
Hello,

With the release of Go 1.19, there is a new update for go4.org/unsafe/assume-no-moving-gc, which the Ratelimit module uses.

This has been updated to in 5680eab76769b678f4f9a0ab950dad20af6c4c4a, however, there is no new tagged version. As a result, Caddy's build server uses an earlier version which panics, making it impossible to upgrade unless the Ratelimit module is removed, then re-added using the Master branch after downloading an upgraded version via *caddy upgrade*.

It would be great if you could release a new version of the Ratelimit plugin so that this could be avoided.

Much thanks in advance ☺️

**Comment by RussellLuo** [comment]
@Flameborn You are welcome, and thanks for the report! [ratelimit/v0.2.0](https://github.com/RussellLuo/caddy-ext/releases/tag/ratelimit%2Fv0.2.0) has been released.

**Comment by RussellLuo** [comment]
I'm going to close this issue, feel free to open issues if you have other questions :)
