### ISSUE TITLE
Custom error response

### ISSUE THREAD

**Issue by ermiaqasemi** [RussellLuo/caddy-ext#3]
Hi thanks for developing this, it is too much useful

I just wondering how can I return a custom response when the limit happens?

**Comment by ermiaqasemi** [comment]
FYI, I tried handle_errors but does not work

**Comment by RussellLuo** [comment]
> FYI, I tried handle_errors but does not work

While responding with a 429, `ratelimit` does not return an error (it's `nil` here):

https://github.com/RussellLuo/caddy-ext/blob/cd69136160beae03aed2d670661be7747ccd074e/ratelimit/ratelimit.go#L120-L121

As explained in this issue: https://github.com/caddyserver/caddy/issues/2920#issuecomment-861919284, `handle_errors` is for errors that happen in Caddy.

I think the ideal solution is to check whether the response status code is 429 first (unfortunately not supported by Caddy now); and If it's so, then we trigger an error explicitly by using the [error](https://caddyserver.com/docs/caddyfile/directives/error) directive:

```
@429 status 429
error @429 429
```

Here is a similar response matcher [status](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#status), which is only available in the context of `reverse_proxy`.

**Comment by ermiaqasemi** [comment]
Thanks for explanation @RussellLuo

**Comment by RussellLuo** [comment]
Hi @ermiaqasemi, `rate_limit` now will return an error if a rate limit is exceeded. Here is an example configuration:

```
:8080 {
  handle_errors {
    @429 expression `{http.error.status_code} == 429`
    respond @429 "The request is rejected!"
  }

  route /foo {
    rate_limit {remote.host} 1r/m

    respond 200
  }
}
```

**Comment by ermiaqasemi** [comment]
Thanks @RussellLuo I will check
