### ISSUE TITLE
ratelimit: optionally respond with IETF draft Ratelimit-* headers

### ISSUE THREAD

**Issue by derhuerst** [RussellLuo/caddy-ext#6]
There's an [IETF draft](https://datatracker.ietf.org/doc/draft-ietf-httpapi-ratelimit-headers/) that defines some HTTP headers `Ratelimit-*` which let the client know about how many requests they can make. This should be configurable.

**Comment by RussellLuo** [comment]
Hi @derhuerst, thanks for your attention!

Internally, the `ratelimit` plugin is based on [slidingwindow](https://github.com/RussellLuo/slidingwindow), which leverages Sliding Window Algorithm. AFAIK, the raw implementation of this algorithm - unlike [Token bucket](https://en.wikipedia.org/wiki/Token_bucket) and [Leaky bucket](https://en.wikipedia.org/wiki/Leaky_bucket) - inherently does not apply the limit at an average rate.

Therefore, I guess it's not easy to calculate values for the [RateLimit-*](https://datatracker.ietf.org/doc/draft-ietf-httpapi-ratelimit-headers/) header, or the value for the [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) header (as mentioned [here](https://github.com/RussellLuo/slidingwindow/issues/5#issuecomment-1071944661)).  What do you think?

**Comment by derhuerst** [comment]
If I understand the IETF document correctly, we could at least use [`RateLimit-Policy`](https://www.ietf.org/archive/id/draft-ietf-httpapi-ratelimit-headers-04.html#name-ratelimit-policy).

**Comment by RussellLuo** [comment]
> we could at least use [RateLimit-Policy](https://www.ietf.org/archive/id/draft-ietf-httpapi-ratelimit-headers-04.html#name-ratelimit-policy).

Yes, I think so. But I'm not sure whether it will be useful if we just set this one header 🤔
